name: notam
description: NOTAM Aviation Notice Observation.
version: 0.0.1
repository: https://github.com/andreypudov/notam

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - aviation
  - notam
